import { useState } from 'react';
import { LogIn, UserPlus, X } from 'lucide-react';
import { isValidUsername } from '../hooks/useAuth';

export function AuthPanel({ signIn, signUp, close }: { signIn: (username: string, password: string) => Promise<void>; signUp: (username: string, password: string) => Promise<void>; close: () => void }) {
  const [mode, setMode] = useState<'signIn' | 'signUp'>('signIn'); const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); if (!isValidUsername(username)) return setError('Use 3–24 letters, numbers, or underscores.'); if (password.length < 6) return setError('Password must have at least 6 characters.'); setBusy(true); try { await (mode === 'signIn' ? signIn(username, password) : signUp(username, password)); close(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to sign in.'); } finally { setBusy(false); } };
  return <div className="overlay auth"><button className="close" onClick={close} aria-label="Close account panel"><X /></button><p className="eyebrow">PLAYER ACCOUNT</p><h2>{mode === 'signIn' ? 'Welcome back' : 'Join the flight'}</h2><p className="auth-copy">{mode === 'signIn' ? 'Sign in to sync your scores.' : 'Create a username and password to save scores across devices.'}</p><form onSubmit={submit}><label>Username<input autoComplete="username" value={username} onChange={event => setUsername(event.target.value)} required /></label><label>Password<input type="password" autoComplete={mode === 'signIn' ? 'current-password' : 'new-password'} value={password} onChange={event => setPassword(event.target.value)} required /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{mode === 'signIn' ? <LogIn /> : <UserPlus />}{busy ? 'Please wait…' : mode === 'signIn' ? 'Sign in' : 'Create account'}</button></form><button className="text-button" onClick={() => { setMode(mode === 'signIn' ? 'signUp' : 'signIn'); setError(''); }}>{mode === 'signIn' ? 'New here? Create an account' : 'Already have an account? Sign in'}</button></div>;
}
